### ISSUE TITLE
Review KlerosGovernor

### ISSUE THREAD

**Issue by ferittuncer** [kleros/kleros#128]

**Comment by ferittuncer** [comment]
### Review at 4afdad21ec34bedc7cfddb530e79f823994ba4b8

1. Rename `lastAction` to `lastApprovalTime`.
2. Rename `shadowWinner` to `defaultWinner`.
3. Why `lastAction = 0` ?https://github.com/kleros/kleros/blob/4afdad21ec34bedc7cfddb530e79f823994ba4b8/contracts/kleros/KlerosGovernor.sol#L204-L209
4. Why can't fund an appeal for others' lists? https://github.com/kleros/kleros/blob/4afdad21ec34bedc7cfddb530e79f823994ba4b8/contracts/kleros/KlerosGovernor.sol#L226
5. Instead of iterating all submissions during rule, to detect duplicates; we could iterate during submission to avoid duplicates first place.

Benefits: No need to withdraw, no need to iterate inside ruling and impossible to send a duplicate submission and lose deposit because of it.

Downside: Submissions are going to require more and more gas. However, we can say that normally there won't be more than twenty submissions in a period, so this should be OK.

6. **`require` return value of `call` to be `true`:** https://github.com/kleros/kleros/blob/4afdad21ec34bedc7cfddb530e79f823994ba4b8/contracts/kleros/KlerosGovernor.sol#L313-L314

Instead I suggest: `transaction.executed = transaction.target.call.value(transaction.value)(transaction.data);`

7. **Don't let arbitrary execution order**.
https://github.com/kleros/kleros/blob/4afdad21ec34bedc7cfddb530e79f823994ba4b8/contracts/kleros/KlerosGovernor.sol#L307-L316

Individual transactions in the list may depend on previous ones post-conditions, so the order of execution could change the resulting state. Therefore we should not let execution in arbitrary order.

Also, for the same reason, don't `continue` contract can't execute a transaction when it lacks funds.


FYI @unknownunknown1

**Comment by ferittuncer** [comment]
Awaiting crowdfunding to be implemented to review again.

**Comment by mtsalenc** [comment]
L25: A ruling that was given -> The ruling that was given
L26: given to a dispute of the session. ->  given to the dispute of the session, if any.
L43: Is needed to catch duplicates -> Used to catch duplicates.
L51:  side that ultimately wins a dispute ->  side that won this round of the dispute.
L61: must be paid by submitter in the case -> must be paid by each side in the case
L70: Stores all submitting sessions. -> Stores all submitted sessions.
L199, 201, 205: lisHash -> listHash
L201: Why do we only allow withdrawing from the latest session? Could funds get stuck?

I suggest swapping the positions of calculateContribution() and contribute().

I could not find any vulnerabilities.

**Comment by unknownunknown1** [comment]
L43: I wanted to avoid saying "used to" because it also has another meaning like, "did something in the past on a regular basis", however I think I'll replace "Is needed to" with "Is used to".
L51: I actually took it from TCR and I think it still applies here because to get reward a party have to win a dispute and not a round.
L70: Not sure about this, since "submitted session" implies that we actually submit sessions. "Submitting session" is also not the best wording but I keep it for now.
L201: Regardless, withdrawing also has a timeout of 1 hour so it's bound to be possible only in a current session. And allowing to withdraw lists from previous sessions can cause some vulnerable and unexpected situations I think. Funds won't get stuck, this list will just be treated as a regular submission and go to a dispute.

**Comment by unknownunknown1** [comment]
Made a PR with changes
