### ISSUE TITLE
Make a bot to penalize inactive jurors.

### ISSUE THREAD

**Issue by clesaege** [kleros/kleros#70]

**Comment by marczeller** [comment]
Quite hard task in the current Kleros contract as no available function (to the best of my knowledge) provide the information of selected jurors for a Dispute and associated draws.

- Draws can be easily "bruteforced" by a contract but it's not optimal for gas.

- Jurors can be somewhat "bruteforced" by checking the potential jurors if someone monitor all the ETH address who had activated their PNKs during the current session, but the possibilities often lead to a gas amount needed > of the available "reward"

Mitigation proposal : 
1) Rewrite `function penalizeInactiveJuror(address _jurorAddress, uint _disputeID, uint[] _draws) public {`
in order to automatically withdraw all the "available to steal" PNKs  without the  `address _jurorAddress and uint[] _draws` input parameters (function should still check the information internally)

2) Add a function to reveal the juror address and draws on a dispute with the following input parameters : `function revealJurors(uint _disputeID) public {`
But that might be "sensitive information" and Kleros might consider the first option 😸

**Comment by marczeller** [comment]
Ok, so the bot should call  `function isDrawn(uint _disputeID, address _juror, uint _draw)` and "bruteforce" it with all addresses that called the function `function activateTokens` and all possible draws in order to create a listing of possible jurors in the current period (**that doesn't cost any gas**)

then `function getVoteCount` can provide information about "inactive jurors slots". (**also no gas cost**)

Lastly the bot simply call `function penalizeInactiveJuror` onchain with collected information, it's quite gas effective. 👍

**Comment by clesaege** [comment]
Yeah, this way there is only a O(1) on chain cost.

**Comment by epiqueras** [comment]
This will be done on chain with the new release.
