### ISSUE TITLE
IsDrawn function return "false negative" results after PassPeriod

### ISSUE THREAD

**Issue by marczeller** [kleros/kleros#91]
with `0x211F01e59b425253C0a0E9a7Bf612605b42ce82c` juror contract, calling the function `Isdrawn` return `false` on every drawn juror after the `PassPeriod` function is executed.

Resulting of no (to the best of my knowledge) way to know previous periods jurors draws.

But we need the draws in order to call  `penalizeInactiveJuror` otherwise the only way to successfully collect every juror draws is do call `isdrawn` on every address that called `activatetokens` before the voting period end. 

Mitigation proposal : 
Turn `isDrawn` to a Period-agnostic function with an additional input parameter `uint  _appeals` or add another public read function with this feature.

**Comment by satello** [comment]
Right now the only way to do `penalizeInactiveJuror` is to check every address that activated tokens in that session like you mentioned. `isDrawn` works all the way up until the next `activation` period. So all jurors can be checked in `appeal` or `execute` periods after they have, or have not, voted. There is no way to know juror draws in previous sessions/appeals because `randomNumber` is not stored and changes every session. Also `penalizeInactiveJuror` will not work for previous sessions if a juror votes in a future session before it is called.

This is a limitation of the current arbitrator contract. We are working on a new arbitrator that has a session for each dispute, which will allow for juror draws to be logged and recoverable so that draws don't "disappear" in subsequent sessions.
